apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-video
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload-video
  template:
    metadata:
      labels:
        app: upload-video
    spec:
      containers:
      - name: my-container
        image: 761018885655.dkr.ecr.eu-west-2.amazonaws.com/mindcast/uploadvideo:latest
        ports:
        - containerPort: 80